SELECT 
		row_number() OVER (ORDER BY [OBJ_PROP_SETS_UUID]) Id,
		0 Processed,
		--CORE_NAME CORE_NAME1, 
		--APPLICATION_NAME APPLICATION_NAME1, 
		--STAGE_NAME STAGE_NAME1, 
		--GRIP_NAME GRIP_NAME1, 
		--OBJECT_SETS_ID OBJECT_SETS_ID1,
		--OBJECT_TYPE  OBJECT_TYPE1,
		--OBJ_PROP_SETS_ID OBJ_PROP_SETS_ID1, 
		--OBJECT_PROP_TYPE OBJECT_PROP_TYPE1,
		--PROPERTY_NAME PROPERTY_NAME1, 
		--PROPERTY_VALUE PROPERTY_VALUE1,
		--OPTION_VALUE OPTION_VALUE1,
		*
	FROM [CSA].[VW_APPLICATION_OBJECTS]
	WHERE APPLICATIONS_UUID = @I_APPLICATIONS_UUID and OBJECT_LAYER = 'IO Tag'
		and OBJECT_TYPE not in ('Grid Widget', 'JSON Text', 'Button')
		and PROPERTY_NAME in ('ID', 'Required', 'Max', 'Value')
	ORDER BY CORE_NAME, APPLICATION_NAME, STAGES_ID, STAGE_NAME, GRIPS_ID, GRIP_NAME, OBJECT_SETS_ID, OBJ_PROP_SETS_ID, PROPERTY_NAME, PROPERTY_VALUE